package Catan_Diagram;

/**
 * Date: February 9th, 2026
 * Description: The Dice interface represents a generic dice mechanism used to generate a random integer outcome. Implementations define the 
 * specific rolling behavior (e.g., a single die or multiple dice).
 * Code generated by Papyrus Java (base code)
 * Additions and implementation by Eileen Sanchez 
 */
public interface Dice{
	
	/**
	 * Rolls the dice and returns the resulting value.
     * @return an integer representing the outcome of the roll
     */
	public int roll();
}
