// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

public class Edge extends Location{
	private int start;
	private int end;

	public Edge(int start, int end){
        this.start = start;
        this.end = end;
	}
}//end of Edge
