package Catan_Diagram;

/**
 * Date: February 9th, 2026
 * Description: A  composite dice implementation that represents multiple Dice objects rolled together. Each die contributes to the 
 * final outcome, and the total value is the sum of all individual rolls.
 *
 * Code generated by Papyrus Java (base code)
 * Additions and implementation by Eileen Sanchez 
 */

import java.util.List;
import java.util.ArrayList;

public class MultiDice implements Dice {
	/**
	 * Instance Variable: The list of dice contained within this composite dice
	 */
	private final List<Dice> diceSet;

	/**
	 * Constructor: Creates a MultiDice object containing the specified number of dice.
     * Each die is initialized as a RegularDie.
     *
     * @param numOfDice 						the number of dice to include
     * @throws IllegalArgumentException 		if numOfDice < 1
	 */
	public MultiDice(int numOfDice){
		// Making sure the set has at least one die
		if(numOfDice <1){
			throw new IllegalArgumentException("MultiDice must contain at least one die.");
        }

		// Initializing
		this.diceSet = new ArrayList<>();

		// Creating the die objects
		for(int i = 0; i < numOfDice; i++){
			diceSet.add(new RegularDie());
		}
	}

	/**
	 * Rolls all contained dice in the set and returns the total value.
     * @return the sum of all individual die rolls
     */
	@Override
	public int roll(){
		int total = 0;

		// Adding up the rolls
		for(Dice dice: diceSet){
			total += dice.roll();
		}
		return total;
	}
}