// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;


public class Node extends Location{

	private int id;

	public Node(int id){
        this.id = id;
	}
}
