// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

import java.util.List;
import java.util.ArrayList;
/************************************************************/
/**
 * 
 */
public class Board{
	/**
	 * 
	 */
	private List<HexTile> tiles;

	private List<Location> nodes;
	private List<Location> edges;

	/**
	 * 
	 */
	public Board(){
		tiles = new ArrayList<>();
		nodes = new ArrayList<>();
		edges = new ArrayList<>();

		//Create all nodes on board
		for(int i = 0; i<MapSkeleton.nodeCount; i++){
			nodes.add(new Node(i));
		}

		//Create all edges on board
		for(int i = 0; i<MapSkeleton.edges.length; i++){
			edges.add(new Edge(MapSkeleton.edges[i][0], MapSkeleton.edges[i][1]));
		}

		//Create all hex tiles
		for (int tileID = 0; tileID<MapSkeleton.numOfTiles; tileID++){
			Location [] nodesToAdd = new Node [6];
			Location [] edgesToAdd = new Edge [6];
			for(int j = 0; j<6; j++){
				nodesToAdd[j] = nodes.get(MapSkeleton.tileNodes[tileID][j]);
				edgesToAdd[j] = edges.get(MapSkeleton.tileEdges[tileID][j]);
			}

			tiles.add(new HexTile(MapLayout.tileResource[tileID], tileID, MapLayout.tokens[tileID], nodesToAdd, edgesToAdd));
		}

	}

	/**
	 * 
	 * @param token 
	 * @return 
	 */
	public HexTile[] getResourceProdTile(int token){
        HexTile[] producingTiles = {null, null};
        int i = 0;
        for (HexTile currTile: tiles){
            if (currTile.getToken() == token){
                Location[] tileNodes = currTile.getNodes();

                for (Location node : tileNodes){
                    if (node.isOccupied()){ //true
                        producingTiles[i] = currTile;
                        i++;
                    }
                }
            }
        }
        return producingTiles;
	}

    public Node getIDNode(int id){//CH
        for (Location location : nodes) {
            Node n = (Node) location;
            if (n.getId() == id) {  //assuming Node has getId()
                return n;
            }
        }
        return null; // not found
    }

    public Edge getEdgeByIDNodes(int a, int b){//CH
        for (Location location : edges){
            Edge e = (Edge) location; //type casting as Edge
            if ((e.getStart() == a && e.getEnd() == b) || (e.getStart() == b && e.getEnd() == a)){
                return e;
            }
        }
        return null;
    }
}
