// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

public class Edge extends Location{
	private int start;
	private int end;

	public Edge(int start, int end){
        this.start = start;
        this.end = end;
	}

    public int getStart(){//CH
        return start;
    }
    public int getEnd(){//CH
        return end;
    }
}//end of Edge
