// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

import java.util.Scanner;

public class Game{
    /**
     *
     */
    private int maxRounds;
    /**
     *
     */
    private int currentRound;
    /**
     *
     */
    private Board board;
    /**
     *
     */
    private Trader[] agents;
    /**
     *
     */
    private Trader bank;
    /**
     *
     */
    private Dice dice;

    //CH - add CurentPlayer
    private Trader currentPlayer;

    /**
     *
     * @param rounds
     * @param numPlayers
     */
    public Game(int rounds, int numPlayers){//CH - add numPlayers
        this.maxRounds = rounds;

        if (numPlayers < 3 || numPlayers > 4) numPlayers = 4;
        agents = new Agent[numPlayers];

        if (maxRounds > 8192) maxRounds = 8192;
        for (int i = 0; i < numPlayers; i++){
            agents[i] = new Agent(i+1);
        }

        board = new Board();
        bank = new Bank();
        dice = new MultiDice(2);
    }//end of Game constructor

    /**
     *
     */
    public void run(){
        Scanner scanner  = new Scanner(System.in);
        initialSetup(scanner);

        for(currentRound = 0; currentRound <= maxRounds; currentRound++){
            for (Trader agent : agents){
                currentPlayer = agent;
                System.out.println("\nPlayer " + ((Agent)agent).getId() + " turn\n");
                int rollSum = dice.roll();
                System.out.println("The dice sum: " + rollSum);
                /* Production Step */
                if (rollSum != 7) produceResource(rollSum);

                /* Building Step */
                System.out.println("Would you like to build anything (yes/no): ");
                String buildSomthing = scanner.nextLine().toLowerCase();
                if (buildSomthing.equals("yes")){
                    boolean builtSomething = build(scanner);

                    if(builtSomething) System.out.println("\nBuild was successful.");
                    else System.out.println("\nNothing was built.");
                }
            }//end of each agent's turn

            /* Checking Victory Point status of each player */
            int winnerID = -1;
            System.out.println("Player's Victory Points: ");
            for (Trader agent : agents){
                int agentVicPoints = ((Agent) agent).getVictoryPoints();
                System.out.println("Player " + ((Agent) agent).getId() + ": " + agentVicPoints);
                if (agentVicPoints >= 10){
                    winnerID = ((Agent) agent).getId();
                    currentRound = maxRounds + 1; //breaks the rounds loop
                    break; //gets out of for each loop
                }
            }//end of for each (check eac player's vicpoints)

            if (winnerID != -1){
                System.out.println("Player " + winnerID + "wins the Game!");
            }//end of if (win message)
        }//end of for loop (max round loop)
    }//end of run()


    //find the hextile that has that corresponding token
    //from that hextile, get his array of nodes
    //from that, loop through the node to see if any of the node is occupied
    //if that node is occupied, then get array from each agent to get their array of infrastructure
    //from that, check if the node that we currently have (as occupied) matches any of the agent's infrastructure node (whether that is city or node)
	private void produceResource(int token){
        HexTile[] producingTiles = board.getResourceProdTile(token); //getting the relevant hextiles

        for (HexTile currTile : producingTiles){
            if (currTile != null){

                Location[] tileNodes = currTile.getNodes(); //get nodes of that tile
                ResourceType resourceType = currTile.getResourceType();

                //Loop over each agent
                for (Trader agentTrader : agents){
                    Agent agent = (Agent) agentTrader;

                    //Loop over each infrastructure of the agent
                    for (int i=0; i < agent.getInfraCount(); i++){
                        Infrastructure infra = agent.getInfrastructure()[i]; //getting each infrastructure that the agent has currently

                        //Check if that infrastructure is on this tile
                        for (Location node : tileNodes){
                            if (infra.getLocation() == node){
                                int amount = (infra instanceof City) ? 2 : 1; //if city, then it produces 2*resource, otherwise it's a settlement which gives 1*resource
                        
                                //Give the agent the resource
                                for (int j=0; j<amount; j++){
                                    Card cardFromBank = bank.removeCard(resourceType); //remove the card from the bank
                                    if (cardFromBank != null){ //checking if the bank had at least one card to give to the agent
                                        agent.addCard(cardFromBank);
                                        System.out.println("Player " + agent.getId() + " gets " + resourceType + ".");
                                    } else {
                                        System.out.println("Bank is out of " + resourceType + " cards!");
                                    }
                                }

                                break; //stop checking for other nodes for this infra
                            }
                        }
                    }
                }
            }
        }
	}

    public boolean build(Scanner scanner){
        int buildChoice;
        do{
            System.out.println("0 = Build ROAD");
            System.out.println("1 = Build SETTLEMENT");
            System.out.println("2 = Build CITY");
            System.out.println("3 = NO Build");
            System.out.print("Choice: ");

            buildChoice = scanner.nextInt();
            scanner.nextLine();

            if (buildChoice == 3){
                return false;
            }

            boolean legalBuild = false;

            if (buildChoice == 0) { // Road
                Location buildTarget = roadEdgeInput(scanner);
                legalBuild = canBuildRoad((Edge) buildTarget);

                if (!legalBuild) {
                    System.out.println("Illegal build.");
                    return false;
                }

                //Check and deduct resources first
                if (!resourcePayement(buildChoice)) {
                    System.out.println("Insufficient resources.");
                    return false;
                }
                //Attempt to build
                try {
                    ((Agent) currentPlayer).buildRoad(buildTarget);
                    return true;   // success – resources already deducted
                }
                catch (IllegalStateException e) {
                    //Build failed so refund the resources
                    refundResources(buildChoice);
                    System.out.println("Build failed: " + e.getMessage());
                    return false;
                }
            }//end of Road

            else if (buildChoice == 1){//Settlement
                Location buildTarget = buildingNodeInput(scanner); //get user's input for location of settlement
                legalBuild = canBuildSettlement((Node) buildTarget); //Checks if the user can build settlement at target

                if (!legalBuild){
                    System.out.println("Illegal build.");
                    return false;
                }
                //Check and deduct resources first
                if (!resourcePayement(buildChoice)) {
                    System.out.println("Insufficient resources.");
                    return false;
                }
                //Attempt to build
                try {
                    ((Agent) currentPlayer).buildSettlement(buildTarget);
                    return true;   // success – resources already deducted
                }
                catch (IllegalStateException e) {
                    //Build failed so refund the resources
                    refundResources(buildChoice);
                    System.out.println("Build failed: " + e.getMessage());
                    return false;
                }
            }//end building Settlement
            else if (buildChoice == 2){//City
                Location buildTarget = buildingNodeInput(scanner); //get user's input for location of settlement
                legalBuild = canBuildCity((Node) buildTarget);

                if (!legalBuild){
                    System.out.println("Illegal build.");
                    return false;
                }

                //Check and deduct resources first
                if (!resourcePayement(buildChoice)) {
                    System.out.println("Insufficient resources.");
                    return false;
                }
                //Attempt to build
                try {
                    ((Agent) currentPlayer).buildCity(buildTarget);
                    return true;   // success – resources already deducted
                }
                catch (IllegalStateException e) {
                    //Build failed so refund the resources
                    refundResources(buildChoice);
                    System.out.println("Build failed: " + e.getMessage());
                    return false;
                }
            }//end building City
            else System.out.println("Invalid choice. Try Again");
        } while (true);

    }//end of build()
    private boolean resourcePayement(int toBuild){ //CH - change to boolean return

        ResourceType[][] materials = {
                {ResourceType.BRICK, ResourceType.LUMBER}, //Road
                {ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL}, //Settlement
                {ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE} //City
        };

        ResourceType[] recipe = materials[toBuild];

        int[] original = currentPlayer.getResourceCount(); //gets player's array
        int[] temp = new int[original.length];
        //copy count over
        System.arraycopy(original, 0, temp, 0, original.length);

        for (ResourceType type : recipe){
            int index = type.getIndex();
            temp[index]--;

            if (temp[index] < 0) {
                return false;  //not enough resources
            }
        }//end of for each

        for (ResourceType type : recipe) {
            Card transitionCard = currentPlayer.removeCard(type);
            bank.addCard(transitionCard);
        }
        return true;
    }//end of build
    private void refundResources(int toBuild) {
        ResourceType[][] materials = {
                {ResourceType.BRICK, ResourceType.LUMBER},
                {ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL},
                {ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE}
        };
        ResourceType[] recipe = materials[toBuild];
        for (ResourceType type : recipe) {
            //Remove one card of this type from the bank
            Card card = bank.removeCard(type);
            //Give it back to the player
            (currentPlayer).addCard(card);
        }
    }


    private Location roadEdgeInput(Scanner s){ //CH
        Edge edge = null;

        while (edge == null){
            System.out.print("Enter start node ID: ");
            int a = s.nextInt();
            s.nextLine();

            System.out.print("Enter end node ID: ");
            int b = s.nextInt();
            s.nextLine();

            edge = board.getEdgeByIDNodes(a, b);

            if (edge == null)System.out.println("Invalid node IDs. Please try again."); // if edge is still null after method, the search failed
        }
        return edge;
    }
    private Location buildingNodeInput(Scanner s){//CH
        Node node = null;

        while (node == null){
            System.out.print("Enter node ID: ");
            int id = s.nextInt();
            s.nextLine();
            //s.nextLine();

            node = board.getIDNode(id);

            if (node == null){// if node is still null after method, the search failed
                System.out.println("Invalid node ID. Please try again.");
            }
        }
        return node;
    }

    private boolean canBuildRoad(Edge edge){//CH
        Agent player = (Agent) currentPlayer; //type casting to use Agent methods, not just Trader
        if (edge.isOccupied()) return false;

        int a = edge.getStart();
        int b = edge.getEnd();

        //Check player's infrastructure
        for (int i = 0; i < player.getInfraCount(); i++) {
            Infrastructure infra = player.getInfrastructure()[i];
            Location loc = infra.getLocation();

            //Connected to player's settlement/city
            if (loc instanceof Node){
                Node n = (Node) loc;
                if (n.getId() == a || n.getId() == b) return true;
            }

            //Connected to player's road
            if (loc instanceof Edge) {
                Edge e = (Edge) loc;
                boolean isConnected = (e.getStart() == a || e.getStart() == b || e.getEnd() == a   || e.getEnd() == b);
                if (isConnected){
                    //finds the shared node ID
                    int sharedNode;
                    if (e.getStart() == a || e.getEnd() == a) sharedNode = a;
                    else sharedNode = b;

                    //If shared node is occupied by ANOTHER player - build should fail
                    for (Trader players : agents){
                        Agent enemyPlayer = (Agent) players;
                        if (enemyPlayer == player) continue; //no need to check if the node is the currplayer's or not

                        for (int j = 0; j < enemyPlayer.getInfraCount(); j++){
                            Infrastructure otherInfra = enemyPlayer.getInfrastructure()[j];

                            if (otherInfra instanceof Settlement || otherInfra instanceof City){
                                Node otherNode = (Node) otherInfra.getLocation();
                                if (otherNode.getId() == sharedNode){
                                    return false; //build has been blocked by enemy building
                                }
                            }
                        }//end of for loop
                    }
                    return true;
                }
            }
        }//end of for loop (checking player's infrastructures)
        return false;
    }//end of canBuildRoad

    private boolean canBuildSettlement(Node node){ //Ch
        Agent player = (Agent) currentPlayer;
        if (node.isOccupied()) return false;

        int nodeId = node.getId();

        //must connect to player's existing road
        boolean connectedToRoad = false;

        for (int i = 0; i < player.getInfraCount(); i++) {
            Infrastructure infra = player.getInfrastructure()[i];

            if (infra instanceof Road){
                Edge e = (Edge) infra.getLocation();

                if (e.getStart() == nodeId || e.getEnd() == nodeId) {
                    connectedToRoad = true;
                    break;
                }
            }
        }//end of for loop (checking player's infrastructures)

        if (!connectedToRoad) return false;

        if (!noAdjacentSettlements(node)) return false;

        return true;
    }//end of canBuildSettlement()
    private boolean canBuildCity(Node node){//CH
        Agent player = (Agent) currentPlayer;
        for (int i = 0; i < player.getInfraCount(); i++){
            Infrastructure infra = player.getInfrastructure()[i];
            //Checking if the infra. is a settlement and has the same location as where the player wants to place City
            if (infra instanceof Settlement && infra.getLocation() == node) return true;
        }//end of for loop (checking player's infrastructures)
        return false;
    }//end of canBuildCity()



    private void initialSetup(Scanner scanner){
        //Forward order
        for (Trader agent : agents){
            currentPlayer = agent;
            System.out.println("\nPlayer " + ((Agent)agent).getId() + " setup turn\n");

            Node settlementSpot = setupSettlementInput(scanner);
            ((Agent)currentPlayer).buildSettlement(settlementSpot);

            Edge roadSpot = setupRoadInput(scanner, settlementSpot);
            ((Agent)currentPlayer).buildRoad(roadSpot);
        }//end of forward turn order of players

        //Reverse Order
        for (int i = agents.length - 1; i >= 0; i--){
            currentPlayer = agents[i];
            System.out.println("\nPlayer " + ((Agent)currentPlayer).getId() + " secondary setup turn\n");

            Node settlementSpot = setupSettlementInput(scanner);
            ((Agent)currentPlayer).buildSettlement(settlementSpot);

            Edge roadSpot = setupRoadInput(scanner, settlementSpot);
            ((Agent)currentPlayer).buildRoad(roadSpot);

            //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Give starting resources!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        }//end of backwards turn order of players
    }//end of initialSetup()

    private Node setupSettlementInput(Scanner scanner){
        while (true){
            Node node = (Node) buildingNodeInput(scanner);
            if (node.isOccupied() || !noAdjacentSettlements(node)){
                System.out.println("Illegal build.");
                continue; //Get user input again
            }
//            if (!noAdjacentSettlements(node)){
//                System.out.println("Illegal build");
//                continue;
//            }
            return node;
        }
    }//end of setupSettlementInput

    private Edge setupRoadInput(Scanner scanner, Node settlement){
        while (true){
            Edge edge = (Edge) roadEdgeInput(scanner);
            if (edge.isOccupied()){
                System.out.println("Illegal build.");
                continue;
            }
            int a = edge.getStart();
            int b = edge.getEnd();

            if (a == settlement.getId() || b == settlement.getId()){
                return edge;
            }
            System.out.println("Illegal build."); //Road must touch the previously placed settlement
        }
    }//end of setupRoadInput()

    private boolean noAdjacentSettlements(Node node){
        int nodeId = node.getId();

        for (int[] e : MapSkeleton.edges){
            if (e[0] == nodeId || e[1] == nodeId){

                int neighborId;
                if (e[0] == nodeId) neighborId = e[1];
                else neighborId = e[0];

                Node neighbor = board.getIDNode(neighborId);
                if (neighbor.isOccupied()) return false;
            }
        }
        return true;
    }//end of noAdjacentSettlements()
}//end of Game class