// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

/**
 * Class representing a tile on the game board.
 */
public class HexTile{

    private ResourceType resourcetype;
    private int landTileID;
    private int token;
    private Location[] nodes;
    private Location[] edges;

    /**
     *
     * @param resource
     * @param landTileID
     * @param token
     * @param nodes
     * @param edges
     */
    public HexTile(ResourceType resource, int landTileID, int token, Location[] nodes, Location[] edges){
        this.resourcetype = resource;
        this.landTileID = landTileID;
        this.token = token;
        this.nodes = new Node[nodes.length];
        this.edges = new Edge[edges.length];
        for (int i = 0; i < nodes.length; i++){
            this.nodes[i] = nodes[i];
            this.edges[i] = edges[i];
        }
    }//end of HexTile Constructor

    public Location[] getNodes(){
        return nodes;
    }

    public Location[] getEdges(){
        return edges;
    }

    public ResourceType getResourceType(){
        return resourcetype;
    }

    public int getlandTileID(){
        return landTileID;
    }

    public int getToken(){
        return token;
    }
}//end of HexTile class
