// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;
public class HexTile{

    private ResourceType resourcetype;

    private int landTileID;

    private int token;

    private Location[] nodes;

    private Location[] edges;

    public Location[] location;

    /**
     *
     * @param resource
     * @param landTileID
     * @param token
     * @param nodes
     * @param edges
     */
    public HexTile(ResourceType resource, int landTileID, int token, Location[] nodes, Location[] edges){
        this.resourcetype = resource;
        this.landTileID = landTileID;
        this.token = token;
        this.nodes = new Node[nodes.length];
        this.edges = new Edge[edges.length];
        for (int i = 0; i < nodes.length; i++){
            this.nodes[i] = nodes[i];
            this.edges[i] = edges[i];
        }
    }//end of HexTile Constructor

    /**
     *
     * @return
     */
    public Location[] getNodes(){
        return nodes;
    }

    /**
     *
     * @return
     */
    public Location[] getEdges(){
        return edges;
    }

    /**
     *
     * @return
     */
    public ResourceType getResourceType(){
        return resourcetype;
    }

    /**
     *
     * @return
     */
    public int getlandTileID(){
        return landTileID;
    }

    /**
     *
     * @return
     */
    public int getToken(){
        return token;
    }
}//end of HexTile class
