// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

/************************************************************/
/**
 * A class to define a template for roads, settlements, and cities
 */
public abstract class Infrastructure{
    private int victoryPoints;
    private Agent owner;
    private Location location;

    public Infrastructure(int victoryPoints, Agent owner){
        this.victoryPoints = victoryPoints;
        this.owner = owner;
    }

    public abstract void build(Location location);
    public int getVictoryPoints(){
        return victoryPoints;
    }

    public Agent getOwner(){
        return owner;
    }

    public void setLocation(Location location){
        this.location = location;
    }

    public Location getLocation(){
        return location;
    }
}