// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

public abstract class Location{
	private boolean occupied;

    public Location(){
        this.occupied = false;
    }

	public boolean isOccupied(){
        return occupied;
	}

	public void setOccupied(){
        this.occupied = true;
	}

}//end of Location class
