// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

/**
 * A class to define the attributes and behaviours of a location that can be built by a player.
 */

public abstract class Location{
	private boolean occupied;

    public Location(){
        this.occupied = false;
    }

	public boolean isOccupied(){
        return occupied;
	}

	public void setOccupied(){
        this.occupied = true;
	}

}//end of Location class
