// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;


public class Node extends Location{

	private int id;

	public Node(int id){
        this.id = id;
	}

    public int getId(){//CH
        return id;
    }
}
