package src;

/**
 * Date: February 9th, 2026
 * Description: A standard six‑sided die implementation of the Dice interface. This class encapsulates the behavior of a single die that 
 * produces a random value between 1 and 6 each time it is rolled.
 *
 * Code generated by Papyrus Java (base code)
 * Additions and implementation by Eileen Sanchez 
 */
import java.util.Random;

public class RegularDie implements Dice{
	/**
	 * Instance Variable: our random generator
	 */
	private Random myRandomRandy;

	/**
	 * Constructor:  Creates a new six‑sided die with its own random number generator.
	 */
	public RegularDie(){
		this.myRandomRandy = new Random();
	}

	/**
	 * Rolls the dice and returns the resulting value.
     * @return an integer representing the outcome of the roll
     */
	@Override
	public int roll(){
		// Returns an integer between 1 and 6
		return myRandomRandy.nextInt(6)+1; 
	}
}
