// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

/************************************************************/
/**
 * 
 */
public class ResourceCard implements Card{
	/**
	 * 
	 */
	private ResourceType resourceType;

	/**
	 * Constructs a resource card
	 * @param type The type of resource card to be created
	 */
	public ResourceCard(ResourceType type){
		this.resourceType = type;
	}

	/**
	 * 
	 * @return resource produced by card
	 */
	public String getCardType(){
		return resourceType.toString();
	}
}
