// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package src;

/************************************************************/
/**
 * 
 */
public enum ResourceType {
	/**
	 * 
	 */
	BRICK(0),
	/**
	 * 
	 */
	ORE(1),
	/**
	 * 
	 */
	WOOL(2),
	/**
	 * 
	 */
	LUMBER(3),
	/**
	 * 
	 */
	GRAIN(4),
	/**
	 * 
	 */
	DESERT(5);

	private int index;

	private ResourceType(int index){
		this.index = index;
	}

	public int getIndex(){
		return index;
	}

}
